### ISSUE TITLE
登录后桌面中间会出现一个灰色或黑色方框？？？

### ISSUE THREAD

**Issue by isfong** [bestwu/docker-wechat#1]
登录后桌面中间会出现一个灰色/黑色方框？？？

**Comment by bestwu** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=171818&extra=

**Comment by isfong** [comment]
其实在dock对应的黑框红酒杯图标那里右键 退出 然后再点一下这个图标黑框就最小化了, （dock必须设置点击动作是最小化）;
大佬能不能麻烦您再移植一个deepin版的有道词典呢？表示Ubuntu18.4 list 上目前是没有办法运行 有道词典的，明明依赖全解决安装成功，但是就是打不开，谢谢了～！

**Comment by isfong** [comment]
`
有黑框的时候，在输入框输入可以提示处表情的文字（比如：666）可以去掉黑框 
`
6楼回复：https://bbs.deepin.org/forum.php?mod=viewthread&tid=154933&highlight=%E5%BE%AE%E4%BF%A1

**Comment by Pencil-Yao** [comment]
> `有黑框的时候，在输入框输入可以提示处表情的文字（比如：666）可以去掉黑框 `
> 6楼回复：https://bbs.deepin.org/forum.php?mod=viewthread&tid=154933&highlight=%E5%BE%AE%E4%BF%A1

链接失效了，能说下解决的方法吗
