### ISSUE TITLE
$HOME 在 docker-compose.yaml 里面不起作用

### ISSUE THREAD

**Issue by guyuming76** [bestwu/docker-wechat#28]
- $HOME/WeChatFiles:/WeChatFiles
这一句，我这里用在 docker run 下是可以的；
但用在 docker-compose 的 yaml 里就不行了。 在yaml里把 $HOME 的实际值写进去是可以的。

Docker version 19.03.8, build afacb8b7f0
docker-compose version 1.27.4, build 40524192

**Comment by bestwu** [comment]
docker-compose.yml 不支持变量，README已修改
