### ISSUE TITLE
如何启动图形界面

### ISSUE THREAD

**Issue by xz-dev** [bestwu/docker-wechat#3]
环境： Arch Linux
docker 容器可以运行，但是无图形界面
请问应该如何正确启动？

![截图](https://user-images.githubusercontent.com/32761048/54511667-9ecd1400-498c-11e9-9193-e4e5ad53b724.png)

![截图](https://user-images.githubusercontent.com/32761048/54511931-7f82b680-498d-11e9-892d-50ca205f189e.png)

**Comment by bestwu** [comment]
xhost + 没有成功

**Comment by xz-dev** [comment]
我安装了相应软件，又尝试了一遍，还是不显示界面
桌面环境：KDE5
![图片](https://user-images.githubusercontent.com/32761048/54588198-3e59d780-4a5d-11e9-84e9-4fccd8958e9d.png)
![图片](https://user-images.githubusercontent.com/32761048/54588191-3a2dba00-4a5d-11e9-81c6-c8c425006008.png)

**Comment by hsyan2008** [comment]
xhost + 没有成功

**Comment by bestwu** [comment]
kde桌面参考 https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/12 配置，目前没时间集成到docker中

**Comment by zx88cvb** [comment]
正解  用 sudo xhost + 后就可以看到图形界面了
