### ISSUE TITLE
Mac下Docker使用报错

### ISSUE THREAD

**Issue by Kianhit** [bestwu/docker-wechat#36]
启动日志如下:
`
kg@kgdeMBP ~ % docker run bestwu/wechat                       
启动 WeChat
Run Deepin-WeChat 2.6.8.65deepin0 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid 
Unable to init server: Could not connect: 拒绝连接

(zenity:34): Gtk-WARNING **: cannot open display: 
Unable to init server: Could not connect: 拒绝连接

(zenity:39): Gtk-WARNING **: cannot open display: 
total 0
lrwxrwxrwx 1 wechat wechat 10 3月  12 10:42 c: -> ../drive_c
lrwxrwxrwx 1 wechat wechat 10 3月  12 10:42 com1 -> /dev/ttyS0
lrwxrwxrwx 1 wechat wechat 10 3月  12 10:42 com10 -> /dev/ttyS9
lrwxrwxrwx 1 wechat wechat 11 3月  12 10:42 com11 -> /dev/ttyS10
lrwxrwxrwx 1 wechat wechat 11 3月  12 10:42 com12 -> /dev/ttyS11
lrwxrwxrwx 1 wechat wechat 11 3月  12 10:42 com13 -> /dev/ttyS12
lrwxrwxrwx 1 wechat wechat 11 3月  12 10:42 com14 -> /dev/ttyS13
lrwxrwxrwx 1 wechat wechat 11 3月  12 10:42 com15 -> /dev/ttyS14
lrwxrwxrwx 1 wechat wechat 11 3月  12 10:42 com16 -> /dev/ttyS15
lrwxrwxrwx 1 wechat wechat 10 3月  12 10:42 com2 -> /dev/ttyS1
lrwxrwxrwx 1 wechat wechat 10 3月  12 10:42 com3 -> /dev/ttyS2
lrwxrwxrwx 1 wechat wechat 10 3月  12 10:42 com4 -> /dev/ttyS3
lrwxrwxrwx 1 wechat wechat 10 3月  12 10:42 com5 -> /dev/ttyS4
lrwxrwxrwx 1 wechat wechat 10 3月  12 10:42 com6 -> /dev/ttyS5
lrwxrwxrwx 1 wechat wechat 10 3月  12 10:42 com7 -> /dev/ttyS6
lrwxrwxrwx 1 wechat wechat 10 3月  12 10:42 com8 -> /dev/ttyS7
lrwxrwxrwx 1 wechat wechat 10 3月  12 10:42 com9 -> /dev/ttyS8
lrwxrwxrwx 1 wechat wechat  8 3月  12 10:42 d:: -> /dev/sdb
lrwxrwxrwx 1 wechat wechat 17 3月  12 10:42 e: -> /media/wayne/Ntfs
lrwxrwxrwx 1 wechat wechat  9 3月  12 10:42 e:: -> /dev/sdb1
lrwxrwxrwx 1 wechat wechat 12 3月  12 10:42 y: -> /home/wechat
lrwxrwxrwx 1 wechat wechat  1 3月  12 10:42 z: -> /
CallApp Deepin-WeChat c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: cannot remove '/home/wechat/.deepinwine/Deepin-WeChat/drive_c/users/wechat/Application Data/Tencent/WeChat/All Users/config/configEx.ini': 没有那个文件或目录
2021年 03月 12日 星期五 10:42:29 UTC:kill WeChat.exe block
2021年 03月 12日 星期五 10:42:29 UTC:tag bottle: 
Traceback (most recent call last):
  File "/opt/deepinwine/tools/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/opt/deepinwine/tools/get_tray_window", line 17, in get_tray_window
    bus = dbus.SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
xprop:  unable to open display ''
2021年 03月 12日 星期五 10:42:29 UTC:active bottles: 
/home/wechat/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
Starting process c:/Program Files/Tencent/WeChat/WeChat.exe ...
[0312/104230:FATAL:temp_window.cc(43)] Check failed: hwnd_. 
Backtrace:
	(No symbol) [0x02C70AB1]
	(No symbol) [0x02B4EB7F]
	(No symbol) [0x02B34861]
	(No symbol) [0x06C61982]
	(No symbol) [0x106AA955]
	(No symbol) [0x101F27FB]
	(No symbol) [0x101F053B]
	(No symbol) [0x106DDED0]
	(No symbol) [0x106DDE09]
	(No symbol) [0x106D9F29]
	(No symbol) [0x106DA4DA]
	(No symbol) [0x1022BD58]
	(No symbol) [0x101F2D12]
	(No symbol) [0x106DF9BE]
	WINPROC_wrapper [0x7E90849A+26]
	(No symbol) [0x7E908B0A]
	(No symbol) [0x7E90ADA5]
	(No symbol) [0x7E8CD4C2]
	(No symbol) [0x7E8D3E3C]
	SendMessageW [0x7E8D4094+84]
	(No symbol) [0x7E8FECF1]
	CreateWindowExW [0x7E8F8138+120]
	(No symbol) [0x106DF5AC]
	(No symbol) [0x106DA270]
	(No symbol) [0x106B638C]
	(No symbol) [0x106B6F99]
	(No symbol) [0x00401918]
	(No symbol) [0x004030B9]
	call_process_entry [0x7B85F80C+12]
	ExitProcess [0x7B860789+3961]
	call_thread_func_wrapper [0x7BC7EEDC+12]
	(No symbol) [0x7BC82089]
	RtlRaiseException [0x7BC7EEBA+74]
	(No symbol) [0x00000000]

退出
`

请问mac下能用这个吗？

**Comment by bestwu** [comment]
不支持mac下使用
