### ISSUE TITLE
LinuxMint19.2启动报错

### ISSUE THREAD

**Issue by xhsky** [bestwu/docker-wechat#5]
Mint19.1运行正常, 但是升级到19.2后, 启动改容器,图形界面一闪而过,后台报错打印如下:
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x13e
  Serial number of failed request:  343
  Current serial number in output stream:  344

**Comment by bestwu** [comment]
是NVIDIA显示吗？
试试

vi /etc/X11/xorg.conf
增加：
 Section "Extensions"
     Option "MIT-SHM" "Disable"
 EndSection

**Comment by ijustyce** [comment]
哈哈，我也遇到了这个问题，解决方案可以看 [X Error of failed request: BadValue (integer parameter out of range for operation) #13](https://github.com/webanck/docker-wine-steam/issues/13) 具体来讲就是 docker run 里 加入 `--ipc="host"` 我 manjaro linux 本来好的，第二天不好了，同样的报错，就是这么解决的。
