### ISSUE TITLE
微信版本过低，无法登录

### ISSUE THREAD

**Issue by Qvistary** [bestwu/docker-wechat#6]
如题

**Comment by CreationLee** [comment]
我也遇到了，希望可以早日解决

**Comment by bestwu** [comment]
深度官方微信包没有升级，可以尝试运行以下脚本（run.sh）手动升级,不保证成功



[update.zip](https://github.com/bestwu/docker-wechat/files/3557922/update.zip)

**Comment by Qvistary** [comment]
> 深度官方微信包没有升级，可以尝试运行以下脚本（run.sh）手动升级,不保证成功
> 
> [update.zip](https://github.com/bestwu/docker-wechat/files/3557922/update.zip)

感谢，成功

**Comment by hsyan2008** [comment]
> 深度官方微信包没有升级，可以尝试运行以下脚本（run.sh）手动升级,不保证成功
> 
> [update.zip](https://github.com/bestwu/docker-wechat/files/3557922/update.zip)

http://packages.deepin.com/deepin/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.8.65deepin0_i386.deb

官方更新了

**Comment by bestwu** [comment]
已更新
