### ISSUE TITLE
增加HIDPI支持

### ISSUE THREAD

**Issue by BoringCat** [bestwu/docker-wechat#7]
根据Winecfg的[文档](https://wiki.winehq.org/Winecfg#Screen_Resolution_.28DPI_Setting.29)，可以通过设置Wine注册表中的LogPixels值来设定DPI值

粗略逻辑代码：
```shell
REGDPI=$(printf '%08x\n' $DPI)
cat > ~/.deepinwine/Deepin-$APP/dpi.reg << EOF
REGEDIT4

[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Hardware Profiles\Current\Software\Fonts]
"LogPixels"=dword:$REGDPI
EOF

WINEPREFIX=~/.deepinwine/Deepin-$APP deepin-wine regedit ~/.deepinwine/Deepin-$APP/dpi.reg
```

其中DPI值由Docker env传入，Wine中默认为96 (0x00000060)

**Comment by Alice-space** [comment]
具体怎么操作呢
不太会搞wine+docker

**Comment by Alice-space** [comment]
https://github.com/Alice-space/docker-wechat
fork中修复

**Comment by Alice-space** [comment]
感谢你的方案

**Comment by BoringCat** [comment]
> https://github.com/Alice-space/docker-wechat
> fork中修复

你的这个方法要多次启动微信，不如看看这个方法

https://github.com/BoringCat/docker-WXWork/blob/c52c340b915a6c2b98f396aa91defe7e9734fbe8/Dockerfile#L28-L29

https://github.com/BoringCat/docker-WXWork/blob/c52c340b915a6c2b98f396aa91defe7e9734fbe8/entrypoint.sh#L15-L18

我觉得修改deepin-wine的启动脚本更加好

**Comment by Alice-space** [comment]
嗯
新的版本我变成改启动脚本了
感谢
