### ISSUE TITLE
无法切换中文输入法且无法传输文件

### ISSUE THREAD

**Issue by backcover7** [bestwu/docker-wechat#9]
系统内用的ibus，可以自由切换，但移到微信内就无法使用中文输入了

#已解决中文输入，修改docker-compose.yml为ibus即可。未解决文件传输问题

**Comment by bestwu** [comment]
不支持拖拽发送文件。使用挂载目录方式，点击发送文件按钮，选择文件

**Comment by Entschuldigung** [comment]
@backcover7 我也遇到这个问题了...请教一下docker-compose.yml在哪里打开
